# Generated by Django 3.2.7 on 2023-02-27 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0002_delete_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Cleaner', 'cleaner'), ('Carpenter', 'carpenter'), ('Babysitter', 'babysitter'), ('Painter', 'painter'), ('Electrician', 'electrician'), ('Elderly Care', 'elderly care'), ('Plumber', 'plumber')], max_length=20, verbose_name='Service')),
                ('price', models.FloatField(default=0)),
                ('booking_count', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('active_status', models.BooleanField(default=True)),
                ('service_provider', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
