# Generated by Django 3.2.7 on 2023-03-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0009_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
