# Generated by Django 3.2.7 on 2023-03-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
