# Generated by Django 3.2.7 on 2023-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230320_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requirement',
            field=models.TextField(blank=True, null=True),
        ),
    ]
