# Generated by Django 3.2.7 on 2023-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0010_serviceprovider_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user/images'),
        ),
    ]
