# Generated by Django 3.2.7 on 2023-02-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('booking_count', models.IntegerField(default=0)),
                ('success', models.IntegerField(default=0)),
                ('active_status', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.service')),
            ],
        ),
    ]
