# Generated by Django 3.2.7 on 2023-02-24 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0004_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='service_provider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
