# Generated by Django 3.2.7 on 2023-02-25 17:36

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0005_serviceprovider_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NE', unique=True, verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Service Provider', 'Service Provider'), ('Clients', 'Clients')], default='Clients', max_length=20, verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.CharField(choices=[('Cleaner', 'cleaner'), ('Carpenter', 'carpenter'), ('Babysitter', 'babysitter'), ('Painter', 'painter'), ('Electrician', 'electrician'), ('Elderly Care', 'elderly care'), ('Plumber', 'plumber')], max_length=20, verbose_name='User Type'),
        ),
    ]
