# Generated by Django 3.2.7 on 2023-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0007_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='service',
            field=models.CharField(choices=[('Cleaner', 'cleaner'), ('Carpenter', 'carpenter'), ('Babysitter', 'babysitter'), ('Painter', 'painter'), ('Electrician', 'electrician'), ('Elderly Care', 'elderly care'), ('Plumber', 'plumber')], max_length=20, verbose_name='Service'),
        ),
    ]
